name: responsive_ui
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  http: ^1.4.0
  retrofit_generator: ^10.0.2
  retrofit: ^4.7.1
  json_annotation: ^4.9.0
  get_it: ^8.2.0
  freezed_annotation: ^3.1.0
  freezed: ^3.2.0
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0
  font_awesome_flutter: ^10.8.0
  json_serializable: ^6.10.0
  build_runner: ^2.6.0

flutter:

  
  uses-material-design: true